name: Linux Build
run-name: Linux Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04 # for GLIBC 2.31
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install -y build-essential git cmake libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
    - name: Configuring CMake
      run: |
        make configure
    - name: Building
      run: |
        make build