name: OSX Build
run-name: OSX Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Configuring CMake
      run: python toolchain.py -c --target Release

    - name: Building
      run: python toolchain.py -b --target Release
