name: OSX Build
run-name: OSX Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configuring CMake
      run: make configure

    - name: Building
      run: make build
