name: Release manually
run-name: Release manually

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  upload-release:

    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]

    steps:
    - uses: actions/checkout@v1

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: uploads

    - name: Update release
      uses: eine/tip@master
      with:
        tag: latest
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./uploads/flappybird-linux.zip ./uploads/flappybird-macos.zip ./uploads/flappybird-windows.zip

  build-linux:

    runs-on: ubuntu-20.04 # for GLIBC 2.31

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt install -y build-essential git cmake libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
    
    - name: Configuring CMake
      run: make configure

    - name: Building
      run: make build

    - name: Zip linux artifact
      run: zip -r flappybird-linux ./bin

    - name: Upload linux artifact
      uses: actions/upload-artifact@v1
      with:
        name: uploads
        path: flappybird-linux.zip

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configuring CMake
      run: make cnofigure

    - name: Building
      run: make build

    - name: Zip macos artifact
      run: zip -r flappybird-macos ./bin

    - name: Upload macos artifact
      uses: actions/upload-artifact@v1
      with:
        name: uploads
        path: flappybird-macos.zip

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure
      run: make configure

    - name: Build
      run: make build

    - name: Zip windows artifact
      run: powershell Compress-Archive bin flappybird-windows.zip

    - name: Upload windows artifact
      uses: actions/upload-artifact@v1
      with:
        name: uploads
        path: flappybird-windows.zip
